package com.nubasu.spotify.webapi.wrapper.api

internal object SpotifyEndpoints {
    const val BASE = "https://api.spotify.com/v1"

    const val ALBUMS = "$BASE/albums"
    const val ARTISTS = "$BASE/artists"
    const val AUDIOBOOKS = "$BASE/audiobooks"
    const val CATEGORIES = "$BASE/browse/categories"
    const val CHAPTERS = "$BASE/chapters"
    const val EPISODES = "$BASE/episodes"
    const val GENRES_SEEDS = "$BASE/recommendations/available-genre-seeds"
    const val MARKETS = "$BASE/markets"
    const val NEW_RELEASES = "$BASE/browse/new-releases"
    const val RECOMMENDATIONS = "$BASE/recommendations"
    const val SEARCH = "$BASE/search"
    const val SHOWS = "$BASE/shows"
    const val TRACKS = "$BASE/tracks"
    const val AUDIO_FEATURES = "$BASE/audio-features"
    const val AUDIO_ANALYSIS = "$BASE/audio-analysis"

    // Me (current-user) endpoints
    const val ME = "$BASE/me"
    const val ME_ALBUMS = "$ME/albums"
    const val ME_ALBUMS_CONTAINS = "$ME/albums/contains"
    const val ME_AUDIOBOOKS = "$ME/audiobooks"
    const val ME_AUDIOBOOKS_CONTAINS = "$ME/audiobooks/contains"
    const val ME_EPISODES = "$ME/episodes"
    const val ME_EPISODES_CONTAINS = "$ME/episodes/contains"
    const val ME_FOLLOWING = "$ME/following"
    const val ME_FOLLOWING_CONTAINS = "$ME/following/contains"
    const val ME_LIBRARY = "$ME/library"
    const val ME_LIBRARY_CONTAINS = "$ME/library/contains"
    const val ME_PLAYER = "$ME/player"
    const val ME_PLAYER_DEVICES = "$ME/player/devices"
    const val ME_PLAYER_CURRENTLY_PLAYING = "$ME/player/currently-playing"
    const val ME_PLAYER_PLAY = "$ME/player/play"
    const val ME_PLAYER_PAUSE = "$ME/player/pause"
    const val ME_PLAYER_NEXT = "$ME/player/next"
    const val ME_PLAYER_PREVIOUS = "$ME/player/previous"
    const val ME_PLAYER_SEEK = "$ME/player/seek"
    const val ME_PLAYER_REPEAT = "$ME/player/repeat"
    const val ME_PLAYER_VOLUME = "$ME/player/volume"
    const val ME_PLAYER_SHUFFLE = "$ME/player/shuffle"
    const val ME_PLAYER_RECENTLY_PLAYED = "$ME/player/recently-played"
    const val ME_PLAYER_QUEUE = "$ME/player/queue"
    const val ME_PLAYLISTS = "$ME/playlists"
    const val ME_SHOWS = "$ME/shows"
    const val ME_SHOWS_CONTAINS = "$ME/shows/contains"
    const val ME_TRACKS = "$ME/tracks"
    const val ME_TRACKS_CONTAINS = "$ME/tracks/contains"
    const val ME_TOP = "$ME/top"

    // Users
    const val USERS = "$BASE/users"
    const val PLAYLISTS = "$BASE/playlists"
}
