package com.nubasu.kotlin_spotify_web_api_wrapper.response.tracks.analysis

data class TrackAnalysis(
    val numSamples: Int,
    val duration: Double,
    val sampleMd5: String,
    val offsetSeconds: Int,
    val windowSeconds: Int,
    val analysisSampleRate: Int,
    val analysisChannels: Int,
    val endOfFadeIn: Double,
    val startOfFadeOut: Double,
    val loudness: Float,
    val tempo: Float,
    val tempoConfidence: Double,
    val timeSignature: Int,
    val timeSignatureConfidence: Double,
    val key: Int,
    val keyConfidence: Double,
    val mode: Int,
    val modeConfidence: Double,
    val codestring: String,
    val codeVersion: Double,
    val echoprintstring: String,
    val echoprintVersion: Double,
    val synchstring: String,
    val synchVersion: Double,
    val rythmstring: String,
    val rythmVersion: Double,
)